2018-05-15 22:20:22.544 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2018-05-15 22:21:55.534 [error] <0.159.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.164.0> exit with reason normal in context child_terminated
2018-05-15 22:22:22.498 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2018-05-16 11:35:14.324 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2018-05-16 11:38:30.203 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2018-05-16 20:19:48.687 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2018-05-16 20:21:59.222 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2018-05-16 20:22:23.318 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2018-05-16 20:28:03.158 [error] <0.145.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.150.0> exit with reason normal in context child_terminated
2018-05-16 20:28:47.051 [error] <0.145.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.150.0> exit with reason normal in context child_terminated
2018-05-16 20:43:10.171 [error] <0.145.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.150.0> exit with reason normal in context child_terminated
2018-05-16 20:43:29.304 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2018-05-16 20:46:27.707 [error] <0.145.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.150.0> exit with reason normal in context child_terminated
2018-05-16 20:46:47.098 [error] <0.145.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.150.0> exit with reason normal in context child_terminated
2018-05-16 20:46:52.937 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2018-05-16 20:52:52.424 [error] <0.145.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.150.0> exit with reason normal in context child_terminated
2018-05-16 20:53:00.515 [error] <0.145.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.150.0> exit with reason normal in context child_terminated
2018-05-16 20:53:10.374 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2018-05-16 20:55:00.658 [error] <0.210.0> gen_server <0.210.0> terminated with reason: {socket_error,timeout}
2018-05-16 20:55:00.658 [error] <0.210.0> CRASH REPORT Process <0.210.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-05-16 20:55:00.665 [error] <0.204.0> gen_server <0.204.0> terminated with reason: {socket_error,timeout}
2018-05-16 20:55:00.665 [error] <0.204.0> CRASH REPORT Process <0.204.0> with 0 neighbours exited with reason: {socket_error,timeout} in gen_server:handle_common_reply/8 line 726
2018-05-16 20:55:00.665 [error] <0.202.0> Supervisor {<0.202.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.203.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.204.0> exit with reason {socket_error,timeout} in context child_terminated
2018-05-16 20:55:00.665 [error] <0.202.0> Supervisor {<0.202.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.203.0>, {amqp_params_network,<<"guest">>,<<"guest">>,<<"/">>,"localhost",5672,0,0,0,infinity,none,[#Fun<amq..>,...],...}) at <0.204.0> exit with reason reached_max_restart_intensity in context shutdown
2018-05-16 20:55:00.666 [error] <0.203.0> Supervisor {<0.203.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.5600>, <0.204.0>, <0.208.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:40295 -> 127.0.0.1:5672">>) at <0.210.0> exit with reason {socket_error,timeout} in context child_terminated
2018-05-16 20:55:00.666 [error] <0.203.0> Supervisor {<0.203.0>,amqp_connection_type_sup} had child main_reader started with amqp_main_reader:start_link(#Port<0.5600>, <0.204.0>, <0.208.0>, {method,rabbit_framing_amqp_0_9_1}, <<"client 127.0.0.1:40295 -> 127.0.0.1:5672">>) at <0.210.0> exit with reason reached_max_restart_intensity in context shutdown
